name: "iwslt14-deen-bpe"

data:
    src: "de"
    trg: "en"
    train: "test/data/iwslt14/train.bpe.32000"
    dev: "test/data/iwslt14/valid.bpe.32000" 
    test: "test/data/iwslt14/test.bpe.32000"
    level: "bpe"
    lowercase: True
    max_sent_length: 62
    voc_min_freq: 1
    voc_limit: 32000

testing:
    beam_size: 5
    alpha: 1.0

training:
    optimizer: "adam"
    loss: "crossentropy"
    normalization: "tokens"
    learning_rate: 0.0002
    batch_size: 80
    scheduling: "plateau"
    patience: 8
    #clip_grad_norm: 1.0
    weight_decay: 0.0
    decrease_factor: 0.7
    schedule_metric: "loss"
    epochs: 100
    validation_freq: 2000
    logging_freq: 500
    eval_metric: "bleu"
    model_dir: "iwslt14-deen-bpe"
    overwrite: False
    shuffle: True
    use_cuda: True
    max_output_length: 80
    print_valid_sents: 5

model:
    encoder:
        type: "gru"
        embeddings:
            embedding_dim: 620
            scale: False
        hidden_size: 500
        bidirectional: True
        dropout: 0.0
        num_layers: 1
    decoder:
        type: "gru"
        embeddings:
            embedding_dim: 620
            scale: False
        emb_scale: False
        hidden_size: 1000
        dropout: 0.0
        hidden_dropout: 0.2
        num_layers: 1
        input_feeding: True
        bridge: True
        attention: "bahdanau"
