name: "reverse_experiment"

data:
    src: "src"
    trg: "trg"
    train: "test/data/reverse/train"
    dev: "test/data/reverse/dev"
    test: "test/data/reverse/test"
    level: "word"
    lowercase: False
    max_sent_length: 11
    voc_min_freq: 0
    voc_limit: 100
    src_vocab: "reverse_bahdanau_correct/src_vocab.txt"
    trg_vocab: "reverse_bahdanau_correct/trg_vocab.txt"

testing:
    beam_size: 9
    alpha: 1.0

training:
    #load_model: "my_model/3300.params"
    random_seed: 42
    optimizer: "adam"
    loss: "crossentropy"
    learning_rate:  {"mt": 0.001, "corrector": 0.001}
    learning_rate_min: 0.0002
#    clip_grad_val: 1.0
    weight_decay: 0.0
    normalization: batch
    normalize_corrector: False
    clip_grad_norm: 1.0
    batch_size: 11
    scheduling: "plateau"
    patience: 5
    decrease_factor: 0.5
    schedule_after_loss: True
    epochs: 1
    validation_freq: 100
    logging_freq: 20
    eval_metric: "bleu"
    model_dir: "reverse_bahdanau_correct" #_load"
    overwrite: True
    shuffle: True
    use_cuda: False
    max_output_length: 30
    print_valid_sents: 3
   # load_model: "reverse_bahdanau_correct/1000.ckpt"
    loss_weights: {"mt": 1., "corrector": 1.}
    pos_weight: 1  # >1 increases the recall, <1 increases the precision.
    slope_annealing_rate: 1.0

model:
    simulated_marking_function: accuracy # recall, lcs, accuracy
    initializer: "xavier"
    embed_initializer: "normal"
    embed_init_weight: 0.1
    bias_initializer: "zeros"
    init_rnn_orthogonal: False
    lstm_forget_gate: 0.
    encoder:
        type: "lstm"
        embeddings:
            embedding_dim: 16
            scale: False
            freeze: False
        hidden_size: 64
        bidirectional: True
        dropout: 0.1
        num_layers: 1
        freeze: False
    decoder:
        type: "lstm"
        embeddings:
            embedding_dim: 16
            scale: False
            freeze: False
        hidden_size: 64
        dropout: 0.1
        hidden_dropout: 0.1
        num_layers: 1
        input_feeding: True
        bridge: False
        attention: "bahdanau"
        freeze: False
    corrector:
        type: "lstm"
        hidden_size: 64
        num_layers: 1
        dropout: 0.1
        bidirectional: True
        attention: "bahdanau"
        reward_coeff: 5
        shift_rewards: False
        freeze: False
